CREATE TABLE USER_MNG_TBL
(
    USER_ID VARCHAR2(15) NOT NULL,
	PASSWORD VARCHAR2(100) NOT NULL,
	USER_NAME VARCHAR2(50) NOT NULL,
	USER_GENDER VARCHAR2(10),
	
	REGISTER_PROG_ID VARCHAR2(15),
	REGISTER_USER_ID VARCHAR2(15),
	REGISTER_DATE DATE,
	UPDATE_PROG_ID VARCHAR2(15),
	UPDATE_USER_ID VARCHAR2(15),
	UPDATE_DATE DATE,
	
	PRIMARY KEY(USER_ID)
);
